
name: "pagerduty"
description: "Wrapper for ST2 PagerDuty plugin"
tags:
  - pagerduty
  - thirdpartyresource

provider: "pagerduty"

connection_types:
  pagerduty:
    api_key:
      name: "api_key"
      field_type: "input"
      required: true
      placeholder: "PagerDuty API Key"
      input_type: "password"
    service_key:
      name: "service_key"
      field_type: "input"
      required: true
      placeholder: "PagerDuty Service Key"
      input_type: "text"
